export const metadata = {
  title: "First Next.JS",
  description: "Generated By Pooya",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          Header
        </header>
        {children}
        <footer style={{ backgroundColor: "lightcyan", padding: "1rem" }}>
          Footer
        </footer>
      </body>
    </html>
  );
}
