<<<<<<< HEAD
export const metadata = {
  title: "First Next.JS",
  description: "Generated By Pooya",
=======
import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Next.js First Project",
    template: "%s | Next.js",
  },
  description: "Next.js description",
>>>>>>> 946d902245d5b087984f01bb528c3496ab3681f6
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
<<<<<<< HEAD
          Header
        </header>
        {children}
        <footer style={{ backgroundColor: "lightcyan", padding: "1rem" }}>
          Footer
=======
          <p>Header</p>
        </header>
        {children}
        <footer style={{ backgroundColor: "ghostwhite", padding: "1rem" }}>
          <p>Footer</p>
>>>>>>> 946d902245d5b087984f01bb528c3496ab3681f6
        </footer>
      </body>
    </html>
  );
}
